// Package plan writes Terraform and a gap report from a hypervisor-neutral snapshot.
package plan

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/kcorehypervisor/kcore-migrate/internal/inventory"
)

// Write creates dir and writes guests.tf plus gaps.md. It does not talk to a hypervisor.
func Write(dir string, snap inventory.Snapshot) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "guests.tf"), []byte(hcl(snap)), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "gaps.md"), []byte(gaps(snap)), 0o644)
}

func hcl(snap inventory.Snapshot) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by kcore-migrate from source %q.\n", snap.Source)
	b.WriteString("# Review before apply. image_path is empty until disks are converted.\n")
	b.WriteString("# storage_backend is filesystem until the provider accepts Ceph.\n\n")
	seen := map[string]int{}
	for _, g := range snap.Guests {
		id := uniqueIdent(g.Name, seen)
		fmt.Fprintf(&b, "resource \"kcore_vm\" %q {\n", id)
		fmt.Fprintf(&b, "  name          = %q\n", g.Name)
		fmt.Fprintf(&b, "  cpu           = %d\n", g.CPU)
		fmt.Fprintf(&b, "  memory_bytes  = %d\n", g.MemoryBytes)
		b.WriteString("  storage_backend = \"filesystem\"\n")
		fmt.Fprintf(&b, "  storage_size_bytes = %d\n", rootSize(g))
		if len(g.NICs) > 0 {
			b.WriteString("\n")
			for _, n := range g.NICs {
				b.WriteString("  nic {\n")
				fmt.Fprintf(&b, "    network = %q\n", n.Network)
				if n.Model != "" {
					fmt.Fprintf(&b, "    model   = %q\n", n.Model)
				}
				if n.MAC != "" {
					fmt.Fprintf(&b, "    mac_address = %q\n", n.MAC)
				}
				b.WriteString("  }\n")
			}
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func gaps(snap inventory.Snapshot) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Gap report (%s)\n\n", snap.Source)
	b.WriteString("Disk bytes were not copied. Converted images are attached later with image_path.\n\n")
	if len(snap.Guests) == 0 {
		b.WriteString("No guests in this snapshot.\n")
		return b.String()
	}
	for _, g := range snap.Guests {
		fmt.Fprintf(&b, "## %s\n\n", g.Name)
		if g.GuestOS != "" {
			fmt.Fprintf(&b, "- Guest OS: %s\n", g.GuestOS)
		}
		if len(g.Disks) > 1 {
			fmt.Fprintf(&b, "- %d disks; only the first size is written as storage_size_bytes\n", len(g.Disks))
		}
		if len(g.Findings) == 0 {
			b.WriteString("- No source-specific findings\n\n")
			continue
		}
		for _, f := range g.Findings {
			fmt.Fprintf(&b, "- %s\n", f)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func rootSize(g inventory.Guest) int64 {
	if len(g.Disks) == 0 || g.Disks[0].SizeBytes <= 0 {
		return 0
	}
	return g.Disks[0].SizeBytes
}

func uniqueIdent(name string, seen map[string]int) string {
	base := ident(name)
	n := seen[base]
	seen[base] = n + 1
	if n == 0 {
		return base
	}
	return fmt.Sprintf("%s_%d", base, n+1)
}

func ident(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(name) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	s := strings.Trim(b.String(), "_")
	if s == "" {
		s = "guest"
	}
	if s[0] >= '0' && s[0] <= '9' {
		s = "vm_" + s
	}
	return s
}
